### ISSUE TITLE
如何在统一的backbone，例如itransformer下复现TS2vec和TF-C

### ISSUE THREAD

**Issue by fei88kk** [thuml/TimeSiam#4]
1. TS2vec 利用了卷积提取时序信息，并在时间戳维度上做对比学习。如果使用itransformer这种series-wise的嵌入方式，丢失了时间顺序信息，还如何在时间维度上进行对比学习？
2. TF-C基于时序特征提取和频域特征提取，按理来说应该有两个编码器。作者是怎么实现预训练的，难道只微调时序编码器，丢失频域编码器吗？

希望作者给出相关的复现代码。如果不能给，也麻烦说一下复现思路，谢谢！

**Comment by dongjiaxiang** [comment]
你好，谢谢提问。由于已有的时间序列表征学习方法很多都有其特殊设计的backbone，但是不同的backbone在时序任务上初始效果差异较大，直接使用原文不同结构的结果并不合理。为了尽可能的公平比较不同的表征学习方法，我们进行统一的backbone实验时需要基于不同的方法进行一定的修改，如TS2Vec在使用iTransformer做backbone时，我们获取序列级的时序表征后，会额外添加新的Linear层将其映射回时间维度表征后再进行对比学习，在微调时我们会将额外添加的层丢弃，只保留原有的backbone接新的任务头进行微调，由于MLP自然的存在位置关系建模，所以并不会丢失时间顺序信息。而TF-C原文是使用双路结构进行时、频域的一致性对比，在进行下游任务时会同时使用两类表征进行分析，但是如果按照其原有思路使用双路编码器进行微调，这与其他方法的微调方式差距较大，也不是很合理，所以对于TF-C方法我们只使用其中预训练的单个编码器进行下游任务的微调。

**Comment by fei88kk** [comment]
感谢作者的解答，我认为这么做是非常合理的！
